/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as WorkspaceHomeRouteImport } from './routes/_workspace/home'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as WorkspaceProjectsNewRouteImport } from './routes/_workspace/projects/new'
import { Route as WorkspaceProjectsProjectIdRouteImport } from './routes/_workspace/projects/$projectId'

const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceHomeRoute = WorkspaceHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectsNewRoute = WorkspaceProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProjectsProjectIdRoute =
  WorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/home': typeof WorkspaceHomeRoute
  '/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/projects/new': typeof WorkspaceProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/home': typeof WorkspaceHomeRoute
  '/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/projects/new': typeof WorkspaceProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_workspace/home': typeof WorkspaceHomeRoute
  '/_workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/_workspace/projects/new': typeof WorkspaceProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/home'
    | '/projects/$projectId'
    | '/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/home'
    | '/projects/$projectId'
    | '/projects/new'
  id:
    | '__root__'
    | '/_workspace'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_workspace/home'
    | '/_workspace/projects/$projectId'
    | '/_workspace/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/home': {
      id: '/_workspace/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof WorkspaceHomeRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/projects/new': {
      id: '/_workspace/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof WorkspaceProjectsNewRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/projects/$projectId': {
      id: '/_workspace/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceHomeRoute: typeof WorkspaceHomeRoute
  WorkspaceProjectsProjectIdRoute: typeof WorkspaceProjectsProjectIdRoute
  WorkspaceProjectsNewRoute: typeof WorkspaceProjectsNewRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceHomeRoute: WorkspaceHomeRoute,
  WorkspaceProjectsProjectIdRoute: WorkspaceProjectsProjectIdRoute,
  WorkspaceProjectsNewRoute: WorkspaceProjectsNewRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
